<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_zoho_crm"
 *
 * Auto generated by Extension Builder 2017-07-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Plugin for Zoho Api Integration',
    'description' => 'One of the only TYPO3 extension which provides to integrate features of Zoho like add leads all information from typo3 site.',
    'category' => 'plugin',
    'author' => 'Sanjay Chuahan [NITSAN Technologies]',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-9.5.99',
            'powermail' => '2.1.0-9.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
